variables:
    DOCKER_IMAGE: ${REGISTRY_URL}/${REGISTRY_PROJECT}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}
    DOCKER_CONTAINER: ${CI_PROJECT_NAME}
stages:
    - buildandpush
    - deploy
    - showlog

buildandpush:
    stage: buildandpush
    variables:
        GIT_STRATEGY: clone
    before_script:
        - docker login ${REGISTRY_URL} -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
    script:
        - docker build -t $DOCKER_IMAGE .
        - docker push $DOCKER_IMAGE
    tags:
        - lab-server
    only:
        - tags

deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: clone
    before_script:
        - docker login ${REGISTRY_URL} -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
    script:
        - docker pull $DOCKER_IMAGE
        - docker-compose down || true
        - docker-compose up --build -d
    tags:
        - lab-server
    only:
        - tags

showlog:
    stage: showlog
    variables:
        GIT_STRATEGY: none
    script:
        - sleep 20
        - docker-compose logs
    tags:
        - lab-server
    only:
        - tags
